---
new_page_extension: html
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: "/_layouts"
use_front_matter_path: false
file_template: ":filename:"
